// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDajlkslDPzRms6ry1YtLJGjTRoor60_q8',
    appId: '1:33292246362:web:8dd4e58f5a90f3a7efe763',
    messagingSenderId: '33292246362',
    projectId: 'firstfirebase-1c62b',
    authDomain: 'firstfirebase-1c62b.firebaseapp.com',
    storageBucket: 'firstfirebase-1c62b.appspot.com',
    measurementId: 'G-ZXT8S8HJFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UgnriUEXpJf_OrREBEUR2i4K07CwMuc',
    appId: '1:33292246362:android:ab8cbf7b5b4cbabeefe763',
    messagingSenderId: '33292246362',
    projectId: 'firstfirebase-1c62b',
    storageBucket: 'firstfirebase-1c62b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsd-EVX9QHLOq-272kEN9RMka4V_mLzls',
    appId: '1:33292246362:ios:9f22cb50732607ebefe763',
    messagingSenderId: '33292246362',
    projectId: 'firstfirebase-1c62b',
    storageBucket: 'firstfirebase-1c62b.appspot.com',
    iosBundleId: 'com.example.firstfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsd-EVX9QHLOq-272kEN9RMka4V_mLzls',
    appId: '1:33292246362:ios:ec633905278d46ceefe763',
    messagingSenderId: '33292246362',
    projectId: 'firstfirebase-1c62b',
    storageBucket: 'firstfirebase-1c62b.appspot.com',
    iosBundleId: 'com.example.firstfirebase.RunnerTests',
  );
}
